%LET FINAL_EC2_IMPORT = 
"\\mktg-app01\E\cepps\CAD\Reports\06_2018\August_CAD_BTS_2018_final_EC2_06182018.txt";
%LET FINAL_EXPORT_EC2 = 
"\\mktg-app01\E\cepps\CAD\Reports\06_2018\August_CAD_BTS_2018_final_EC2_06182018_TEST.txt";

DATA FINALEC2_TEST;
	SET FINALEC2;
	IF AGE_RANGE_FLAG = "X";
RUN;

DATA FINALEC2_NO_TEST;
	SET FINALEC2;
	IF AGE_RANGE_FLAG = "";
RUN;

PROC SORT 
	DATA = FINALEC2_TEST;
	BY OWNBR;
RUN;

PROC SURVEYSELECT 
	DATA = FINALEC2_TEST SAMPRATE = 0.50 SEED = 3617 
		OUT = TEST_SAMPLE OUTALL METHOD = SRS NOPRINT;
	STRATA OWNBR;
RUN;

PROC SORT 
	DATA = TEST_SAMPLE;
	BY CIFNO;
RUN;

PROC SORT 
	DATA = FINALEC2_NO_TEST;
	BY CIFNO;
RUN;

DATA FINALEC2_TEST; 
	SET TEST_SAMPLE FINALEC2_NO_TEST;
	IF Selected = . THEN Selected = 0;
RUN;

PROC SQL;
	CREATE TABLE FINALEC2_TEST AS
	SELECT BrAcctNo, OwnBr, ClassTranslation, SSNO1_RT7, Cifno, 
		   FIRSTNAME, MIDDLENAME, LASTNAME, Adr1, Adr2, City, State, 
		   ZIP, DOB, OFFER_TYPE, OFFER_AMOUNT, CAMPAIGN_ID, DROPDATE, 
		   EXPIRATIONDATE, VND_DROP, VND_DUP, AGE_RANGE_FLAG, Selected
	FROM FINALEC2_TEST;
QUIT;
RUN;

PROC EXPORT 
	DATA = FINALEC2_TEST OUTFILE = &FINAL_EXPORT_EC2  DBMS = TAB;
RUN;

PROC EXPORT
	DATA = FINALEC2_TEST
		OUTFILE = '\\mktg-app01\E\cepps\CAD\Reports\06_2018\August_CAD_BTS_2018_final_EC2_06182018_TEST.xlsx'
		DBMS = EXCEL;
RUN;